[project]
name = "github-graphrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aditya Kumar", email = "adityakumarsanni.2001@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "groq>=1.7.0",
    "httpx>=0.28.1",
    "langchain-text-splitters>=1.1.2",
    "neo4j-graphrag[google-genai]>=1.19.0",
    "proto-schema-parser>=2.1.0",
    "python-dotenv>=1.2.3",
    "treesitter-chunker>=4.0.0",
]

[project.scripts]
github-graphrag = "github_graphrag:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
